sonar.projectKey=cashrunway-api
sonar.projectName=CashRunway API
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,coverage/**,reports/**,db/**,monitoring/**
sonar.coverage.exclusions=tests/**,src/server.js

# Quality gate expectations for this project
sonar.qualitygate.wait=false
